compile: main.cpp Morphing.cpp Matrix.cpp Delaunay.cpp Point.cpp Triangle.cpp Edge.cpp
	g++ -o ../Program/b.exe main.cpp Morphing.cpp Matrix.cpp Delaunay.cpp Point.cpp Triangle.cpp Edge.cpp -lgdi32 -O3

run: 
	cd ../Program
	b.exe

gdb:
	gdb ../Program/b.exe